### ISSUE TITLE
add windows support

### ISSUE THREAD

**Issue by pedrobraz1990** [convexfi/riskparity.py#10]
Dear all. While using the package in windows, when importing the module, I encounter the folllowing issue:

`ModuleNotFoundError: No module named 'jaxlib'`

After searching for the package installation I found [this thread](https://github.com/google/jax/issues/507) saying that `jaxlib` has no windows support. 

Is it possible to find alternatives?

thanks in advance!

**Comment by beyondstar2015** [comment]
Can not use!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mirca** [comment]
it seems that jax is available for windows users: https://github.com/google/jax#installation.
