### ISSUE TITLE
How to code the constraints to weight ?please give an example

### ISSUE THREAD

**Issue by xueyongtu** [convexfi/riskparity.py#15]
![image](https://user-images.githubusercontent.com/48517087/151707466-18f5d673-7f0f-44c9-8256-bb3253c4e38f.png)

just as the picture shows, we can set constraints on weights, such as DW<=d. Then how to encode the constraints to weights?

**Comment by mirca** [comment]
Hi @xueyongtu, apologies for the delay on this. You can pass the matrices ``D`` and ``C`` and the vectors ``c`` and ``d`` to the ``design`` method of a ``RiskParityPortfolio`` object. See this example: https://mirca.github.io/riskparity.py/tutorials/comparison-with-pyrb.html#Constrained-Risk-Parity
