### ISSUE TITLE
mac install

### ISSUE THREAD

**Issue by microprediction** [convexfi/riskparity.py#17]
#### Problem description
pip install fails

#### Example
pip install riskparityportfolio

#### Environment:
- OSX
- riskparityportfolio current ver on PyPI
- installation method (e.g. pip, source): pip 

## Errror

            The package setup script has attempted to modify files on your system
              that are not within the EasyInstall build area, and has been aborted.
              
              This package cannot be safely installed by EasyInstall, and may not
              support alternate installation locations even if you run its setup
              script by hand.  Please inform the package's author and the EasyInstall
              maintainers to find out if a fix or workaround is available.

**Comment by mirca** [comment]
Hi, thanks for reporting! 

I can't reproduce the issue locally.

Could I know which macOS version are you using?

Would you mind upgrading your ``setuptools`` via e.g. ``pip install --upgrade setuptools`` and trying again?

Thanks!

**Comment by microprediction** [comment]
Hi. 

11.6 Big Sur
Upgrading to setuptools 62.3.2
py 3.8.2

... and it works! Thanks a lot.

**Comment by mirca** [comment]
@microprediction glad it worked :)!
