### ISSUE TITLE
does it support  nonlinear constraints

### ISSUE THREAD

**Issue by nankaimy** [convexfi/riskparity.py#19]
does [riskparity.py](https://github.com/dppalomar/riskparity.py)  support  constraints with nonlinear constraints，such as  w'*Sigma*w<=5%

**Comment by mirca** [comment]
Hi @nankaimy, thanks for reaching out.

At the moment the algorithm doesn't support nonlinear constraints explicitly.  However, for this special case where you want to bound the variance of the optimal portfolio, we do support it as an objective term.  See this tutorial: https://mirca.github.io/riskparity.py/tutorials/including-mean-return-and-variance.html#Adding-the-variance
