### ISSUE TITLE
no attribute 'RiskParityPortfolio'

### ISSUE THREAD

**Issue by davdigioia** [convexfi/riskparity.py#2]
module 'riskparityportfolio' has no attribute 'RiskParityPortfolio'

I get this error after installing new version

**Comment by mirca** [comment]
@davdigioia could you share a minimum reproducible example?

**Comment by mirca** [comment]
@davdigioia I was able to reproduce it, thanks! I will push a bugfix version to pypi later today.

**Comment by mirca** [comment]
@davdigioia in the meantime, could you try installing via source as described in the README?

**Comment by davdigioia** [comment]
The dev one works
