### ISSUE TITLE
win10 python39 has install problem

### ISSUE THREAD

**Issue by nankaimy** [convexfi/riskparity.py#21]
has the installation problem,win10,python 3.9

文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
riskparityportfolio/vanilla.cpp(21): warning C4244: “初始化”: 从“Eigen::EigenBase::Index”转换到“unsigned int”，可能丢失数据
with
[
Derived=Eigen::Matrix<double,-1,1,0,-1,1>
]
riskparityportfolio/vanilla.cpp(21): warning C4244: “初始化”: 从“Eigen::EigenBase::Index”转换到“const unsigned int”，可能丢失数据
with
[
Derived=Eigen::Matrix<double,-1,1,0,-1,1>
]
riskparityportfolio/vanilla.cpp(50): warning C4244: “初始化”: 从“Eigen::EigenBase::Index”转换到“unsigned int”，可能丢失数据
with
[
Derived=Eigen::Matrix<double,-1,1,0,-1,1>
]
riskparityportfolio/vanilla.cpp(50): warning C4244: “初始化”: 从“Eigen::EigenBase::Index”转换到“const unsigned int”，可能丢失数据
with
[
Derived=Eigen::Matrix<double,-1,1,0,-1,1>
]
riskparityportfolio/vanilla.cpp(166): error C2017: 非法的转义序列
riskparityportfolio/vanilla.cpp(166): error C2001: 常量中有换行符
riskparityportfolio/vanilla.cpp(170): error C2143: 语法错误: 缺少“;”(在“}”的前面)
error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\bin\HostX86\x64\cl.exe' failed with exit code 2
----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\myprogram\Anaconda37\envs\py39\python.exe' -u -c 'import io, os, sys,

**Comment by nankaimy** [comment]
or where i can download the win64 py39 wheel?

**Comment by mirca** [comment]
I'm afraid we only provide source distributions, not wheels.

**Comment by nankaimy** [comment]
so how install on windows?

**Comment by nankaimy** [comment]
if delete vanilla.cpp 104-108

#ifdef VERSION_INFO
    m.attr("__version__") = MACRO_STRINGIFY(VERSION_INFO);
#else
    m.attr("__version__") = "dev";
#endif

it works

**Comment by mirca** [comment]
Thanks all for the discussion. I've added a link on the readme that shows how to install jaxlib on windows. I'm also now running builds for windows on github actions.
