### ISSUE TITLE
quadprog issue mac

### ISSUE THREAD

**Issue by microprediction** [convexfi/riskparity.py#24]
Just a note that I think [this PR](https://github.com/quadprog/quadprog/pull/43) may fix install issues here too. 

#### Problem description
Fails to pip install riskparityportfolio

#### Example

       pip install riskparityportfolio

#### Environment:
- OSX
- riskparityportfolio latest
- installation method: pip
-

**Comment by mirca** [comment]
Awesome, thanks for letting us know!

**Comment by mirca** [comment]
the upstream issue in quadprog has been solved. closing this. thanks!
