### ISSUE TITLE
Vanilla Attribute Error

### ISSUE THREAD

**Issue by rafaelcesar7** [convexfi/riskparity.py#3]
#### Problem description
I have been trying to use your package to make risk parity portfolios with ease. Although, I have been facing some issues running the first tutorial. At first I've tried running it with a local installation, then I've moved to Colab environment. Faced the same issue on both situations.

#### Example
```python
!pip check
!pip install pybind11
!pip install riskparityportfolio

import riskparityportfolio as rp

b = df_portfolio_prices_parity

optimum_weights = rp.vanilla.design(cov, b)
```

#### Behavior
Since it was a simple example provided on the documentation, I thought it would be straight-forward execution, but I'm facing the error below:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-12-0745d4c9a058> in <module>()
      8 b = df_portfolio_prices_parity
      9 
---> 10 optimum_weights = rp.vanilla.design(cov, b)

AttributeError: module 'riskparityportfolio' has no attribute 'vanilla'
```

#### Environment:
- Colab environment: running Ubuntu 18.04.3 LTS
- installation method: pip

**Comment by mirca** [comment]
Hi @ralphscoz: thanks for reporting this.

Could you try installing the ``dev`` version as follows:
```
$ git clone https://github.com/dppalomar/riskparity.py.git
$ cd riskparity.py
$ python setup.py install
```

Let me know if the issue still remains.

**Comment by DanielPNewman** [comment]
Hi @mirca, I installed the `dev` version as you say above, but still get the error reported here:
`AttributeError: module 'riskparityportfolio' has no attribute 'vanilla'`

Love the work that you and Daniel Palomar are doing with risk parity by the way, I appreciate it, so thanks!

**Comment by mirca** [comment]
Hi @DanielPNewman, could you show the version of ``riskparityportfolio`` in the output of
``$ pip list``?
Thanks!

**Comment by DanielPNewman** [comment]
Hi @mirca, yes it's: `riskparityportfolio  0.1.2 `

**Comment by mirca** [comment]
@DanielPNewman thanks! I can't seem to be able to reproduce the issue right now, but I will find some time to investigate it soon!

**Comment by mirca** [comment]
@DanielPNewman @ralphscoz in the meantime
```
from riskparityportfolio import vanilla
```
should work!

**Comment by mirca** [comment]
@DanielPNewman @ralphscoz I was able to reproduce the issue. Thanks again for reporting!
It should be solved via
```
$ git clone https://github.com/dppalomar/riskparity.py.git
$ cd riskparity.py
$ pip install -e .
```
Let me know! :)

**Comment by rafaelcesar7** [comment]
Hey guys! Thank you so much for your help! It actually worked.

**Comment by DanielPNewman** [comment]
Nice one @mirca, this works for me too now, thanks :)

**Comment by mirca** [comment]
Thank you for reporting this issue @DanielPNewman @ralphscoz!
